# Generated by Django 4.2.23 on 2025-10-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ceo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='expires_at',
            field=models.DateField(default=2025),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='identify_number',
            field=models.CharField(default=2025, max_length=255),
            preserve_default=False,
        ),
    ]
