# Generated by Django 4.2.23 on 2025-10-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_company_ceo_company_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
