# Generated by Django 6.0.6 on 2026-06-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_company_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='identify_number',
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
