# Generated by Django 5.2.3 on 2025-07-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='user',
        ),
    ]
