# Generated by Django 5.2.3 on 2025-07-19 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_serviceprovider_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_Active',
            new_name='is_active',
        ),
    ]
