# Generated by Django 4.2.23 on 2025-10-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_category_description_en_category_description_ka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_he',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_he',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_he',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_he',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='name_he',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='name_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_he',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='name_he',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='name_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='alt_text_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='alt_text_he',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='alt_text_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
