# Generated by Django 5.2.3 on 2025-07-20 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_blacklist'),
        ('services', '0003_rename_is_active_category_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='name_ka',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='user',
            field=models.ForeignKey(default=1, editable=False, limit_choices_to={'user_type__in': ['provider', 'Service Provider']}, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
    ]
