# Generated by Django 4.2.23 on 2025-10-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_category_description_ar_category_description_he_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='activity',
            field=models.CharField(choices=[('water', 'water activity'), ('land', 'land activity')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
