# Generated by Django 4.2.23 on 2025-10-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_category_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='activity',
            field=models.CharField(choices=[('water', 'Water activity'), ('land', 'Land activity')], max_length=25),
        ),
    ]
