# Generated by Django 6.0.6 on 2026-06-27 10:38

import django.core.validators
import django.db.models.deletion
import services.models.event
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_add_age_prices'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='category',
                    name='description_tr',
                ),
                migrations.RemoveField(
                    model_name='category',
                    name='name_tr',
                ),
                migrations.RemoveField(
                    model_name='city',
                    name='name_tr',
                ),
                migrations.RemoveField(
                    model_name='country',
                    name='name_tr',
                ),
                migrations.RemoveField(
                    model_name='discount',
                    name='name_tr',
                ),
                migrations.RemoveField(
                    model_name='event',
                    name='description_tr',
                ),
                migrations.RemoveField(
                    model_name='event',
                    name='name_tr',
                ),
                migrations.RemoveField(
                    model_name='eventimage',
                    name='alt_text_tr',
                ),
            ]
        ),
        migrations.AddField(
            model_name='event',
            name='event_ticket',
            field=models.CharField(blank=True, choices=[('per hour', 'per hour'), ('per day', 'per day'), ('per kilometer', 'per kilometer'), ('per room', 'per room'), ('per person', 'per person'), ('per car', 'per car'), ('per boat', 'per boat'), ('per driver', 'per driver'), ('per 10 minutes', 'per 10 minutes'), ('per 15 minutes', 'per 15 minutes'), ('per 30 minutes', 'per 30 minutes'), ('per loop', 'per loop')], help_text='Optional ticket pricing/unit type', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_hi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_hi',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_hi',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name_hi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_hi',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='EventAgePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='e.g. Toddler, Teenager, Senior, Student', max_length=50)),
                ('min_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_prices', to='services.event')),
            ],
            options={
                'ordering': ['min_age'],
            },
        ),
        migrations.CreateModel(
            name='EventVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=services.models.event.upload_service_video, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'avi', 'mkv', 'm4v', 'ogv'])])),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='videos', to='services.event')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
