# Generated by Django 5.2.3 on 2025-07-20 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_blacklist'),
        ('services', '0005_alter_serviceprovider_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type__in': ['provider', 'Service Provider']}, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
