# Generated by Django 5.2.3 on 2025-07-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_serviceprovider_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='commision_rate',
            new_name='commission_rate',
        ),
    ]
