# Generated by Django 6.0.6 on 2026-06-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_category_description_tr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventageprice',
            options={'ordering': ['min_age', 'start_time']},
        ),
        migrations.AddField(
            model_name='eventageprice',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Applicable end time (for special type events)', null=True),
        ),
        migrations.AddField(
            model_name='eventageprice',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Applicable start time (for special type events)', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='activity',
            field=models.CharField(choices=[('water', 'Water activity'), ('land', 'Land activity'), ('special', 'Special activity')], max_length=25),
        ),
    ]
