# Generated by Django 5.2.3 on 2025-07-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_rename_commision_rate_serviceprovider_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_ka',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
