# Generated by Django 6.0.6 on 2026-06-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_eventageprice_options_eventageprice_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='seo_description',
            field=models.TextField(blank=True, help_text='SEO Meta Description override', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='seo_title',
            field=models.CharField(blank=True, help_text='SEO Title override', max_length=200, null=True),
        ),
    ]
