# Generated by Django 6.0.6 on 2026-06-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_event_seo_description_event_seo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='adult_price',
            field=models.IntegerField(blank=True, help_text='Optional adult price', null=True),
        ),
    ]
