# Generated by Django 5.2.3 on 2025-07-21 01:31

import services.models.category
import services.models.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_category_description_en_category_description_ka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=services.models.category.upload_category_icon),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(default=1, upload_to=services.models.service.upload_service_image),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=services.models.service.upload_provider_logo),
        ),
    ]
