# Generated by Django 4.2.23 on 2025-08-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_blacklist_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
