# Generated by Django 5.2.3 on 2025-07-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
