# Generated by Django 4.2.23 on 2025-08-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_address_company_email_company_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='mobile',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
