# Generated by Django 5.2.3 on 2025-07-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('provider', 'Service Provider')], default='customer', max_length=20),
        ),
    ]
