"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.21.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv
from pathlib import Path
from corsheaders.defaults import default_headers
import os
from decouple import config

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

USE_I18N = True
USE_L10N = True
USE_TZ = True


LANGUAGE_CODE = 'en'

LANGUAGES = [
    ("en", _("English")),
    ("ka", _("Georgian")),
    ("ru", _("Russian")),
    ("tr", _("Turkish")),   
    ("ar", _("Arabic")),    
    ("he", _("Hebrew")),    
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

MODELTRANSLATION_LANGUAGES = ('en', 'ka', 'ru', 'tr', 'ar', 'he')

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

ASGI_APPLICATION = 'project.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'services',
    'orders',
    'channels',
    'panel',
    'staff',
    'customer',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'modeltranslation',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sessions',
    'rest_framework',
    'corsheaders',
    'django_filters',
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'core.wsgi.application'

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True  
CORS_ALLOW_HEADERS = list(default_headers) + [
    'Authorization',
    'Content-Type',
]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:3000',
    'https://admin.discount.com.ge',
    'https://discount.com.ge',
    'https://control.discount.com.ge'
]

ALLOWED_HOSTS = [
    '127.0.0.1', 
    'localhost',
    'admin.discount.com.ge',
    'control.discount.com.ge',
    'discount.com.ge'
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'https://admin.discount.com.ge',
    'https://discount.com.ge',
    'https://control.discount.com.ge'
]

SESSION_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = None
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  
SESSION_SAVE_EVERY_REQUEST = True

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

MEDIA_URL = '/uploads/' 
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')

DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760
APPEND_SLASH = False

TIME_ZONE = config('DJANGO_TIME_ZONE', default='UTC')
BACKEND_URL = config('BACKEND_URL', default='http://localhost:8000/en')
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000/en')


STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

BOG_BASE_URL = os.getenv("BOG_BASE_URL", "https://api.bog.ge")  


BOG_CLIENT_INN = os.getenv("BOG_CLIENT_INN", "BOG_CLIENT_INN")
BOG_MERCHANT_ID = os.getenv("BOG_MERCHANT_ID", "BOG_MERCHANT_ID")
BOG_TERMINAL_ID = os.getenv("BOG_TERMINAL_ID", "BOG_TERMINAL_ID")


BOG_PUBLIC_KEY = os.getenv("BOG_PUBLIC_KEY", "YOUR_PUBLIC_KEY_HERE")
BOG_SECRET_KEY = os.getenv("BOG_SECRET_KEY", "YOUR_SECRET_KEY_HERE")


BOG_SUCCESS_URL = os.getenv("BOG_SUCCESS_URL", "BOG_SUCCESS_URL")
BOG_FAIL_URL = os.getenv("BOG_FAIL_URL", "BOG_FAIL_URL")

BOG_API_TOKEN = os.getenv("BOG_API_TOKEN", "BOG_API_TOKEN")

BOG_CALLBACK_URL = os.getenv("BOG_CALLBACK_URL", "https://yourdomain.com/api/orders/bog/callback/")