# Generated by Django 5.2.7 on 2025-11-04 17:14

import django.db.models.deletion
import panel.models.slider
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ka', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_tr', models.CharField(max_length=255, null=True)),
                ('title_ar', models.CharField(max_length=255, null=True)),
                ('title_he', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255)),
                ('description_en', models.CharField(max_length=255, null=True)),
                ('description_ka', models.CharField(max_length=255, null=True)),
                ('description_ru', models.CharField(max_length=255, null=True)),
                ('description_tr', models.CharField(max_length=255, null=True)),
                ('description_ar', models.CharField(max_length=255, null=True)),
                ('description_he', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(upload_to=panel.models.slider.upload_slider_image)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.admin')),
            ],
        ),
    ]
