# Generated by Django 5.2.7 on 2025-11-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
