# Generated by Django 6.0.6 on 2026-06-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_slider_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='description_tr',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title_tr',
        ),
        migrations.AddField(
            model_name='slider',
            name='description_hi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_hi',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
