# Generated by Django 6.0.6 on 2026-06-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_payment_status_order_adults_count_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS `orders_orderageprice` (
                `id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY,
                `category_name` varchar(50) NOT NULL,
                `min_age` integer NOT NULL,
                `max_age` integer NOT NULL,
                `price` decimal(10, 2) NOT NULL,
                `quantity` integer NOT NULL,
                `order_id` bigint NOT NULL,
                CONSTRAINT `orders_orderageprice_order_id_fk` FOREIGN KEY (`order_id`) REFERENCES `orders_order` (`id`)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS `orders_orderageprice`;"
        ),
        migrations.AddField(
            model_name='orderageprice',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Applicable end time (for special type events)', null=True),
        ),
        migrations.AddField(
            model_name='orderageprice',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Applicable start time (for special type events)', null=True),
        ),
    ]
