# Generated by Django 6.0.6 on 2026-06-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_payment_status_order_adults_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderageprice',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Applicable end time (for special type events)', null=True),
        ),
        migrations.AddField(
            model_name='orderageprice',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Applicable start time (for special type events)', null=True),
        ),
    ]
